name = "my-hsk-platform"
compatibility_date = "2024-06-01"
pages_build_output_dir = ".next"

# ⚠️ 关键：绑定 D1 数据库
# binding 名称必须叫 "DB"，因为后面的代码里我们用的是 env.DB
[[d1_databases]]
binding = "DB"
database_name = "hsk-db"
database_id = "48979418-85fb-4b67-9f1f-d2c709102e4" # 运行 npx wrangler d1 create hsk-db 获取
